from utils import call_llm, batch_call_llm
import tempfile

INS = ""
with open("prompts/extscus.txt", "r") as f:
    INS = f.read().strip()

def get_scus(summary:str, model:str):
    try:
        scus = call_llm(INS, summary, model)
        return scus
    except Exception as e:
        print(f"Error generating SCUs for model {model}: {e}")
        return None

def get_batch_scus(batch_summaries:dict[str, list[str]], model:str, clip:int = 2):
    """
    This function generates SCUs for a batch of summaries from multiple models.
    - batch_summaries: A dictionary where keys are model names and values are lists of summaries generated by those models.
    - model: The LLM model to use for generating SCUs.
    - clip: The number of batches to split the summaries into for processing. Must be >= 1. If clip=1, all summaries are processed in a single batch.
    """
    if clip < 1:
        raise ValueError(f"clip must be >= 1, got {clip}")

    summaries = []
    summaries_tag = []
    for m, s in batch_summaries.items():
        print(f"{m} - Summaries count: {len(s)}")
        summaries.extend(s)
        summaries_tag.extend([str(m)] * len(s))

    print(f"Total summaries count: {len(summaries)}")
    print(f"Sample tag: {summaries_tag[:5]}, {summaries_tag[100:105]}")

    scus_res = {}
    if not summaries:
        print("No summaries found to generate SCUs.")
        return scus_res

    total = len(summaries)
    chunk_size = (total + clip - 1) // clip
    batch_scus = []
    for i in range(clip):
        start = i * chunk_size
        end = min(start + chunk_size, total)
        if start >= end:
            break
        with tempfile.TemporaryDirectory(prefix=f"scu_batch_{i}_") as tmp_dir:
            batch_scus.extend(
                batch_call_llm(INS, summaries[start:end], model, tmp_dir, is_raw=True)
            )

    for tag, scu in zip(summaries_tag, batch_scus):
        if tag not in scus_res:
            scus_res[tag] = []
        if ": " in scu:
            scu = " ".join(scu.split(": ")[1:]).strip()
        scus_res[tag].append(scu)

    return scus_res


SAMPLE_SUMMARY = "The Eiffel Tower, located in Paris, was completed in 1889 and stands 330 meters tall."

SAMPLE_BATCH_SUMMARIES = {
    "gpt-4o-mini": [
        "The Eiffel Tower, located in Paris, was completed in 1889 and stands 330 meters tall.",
        "Mount Everest, on the border of Nepal and Tibet, is the highest mountain on Earth at 8,849 meters.",
    ],
    "claude-3-haiku": [
        "The Great Wall of China stretches over 21,000 kilometers and was built across several dynasties.",
        "The Amazon rainforest spans nine countries and produces around 20% of the world's oxygen.",
    ],
}

import argparse
def get_args():
    parser = argparse.ArgumentParser(
        description="Sample runner for get_scus() / get_batch_scus(). "
                    "Use --batch to try the batch sample instead of the single-summary sample."
    )
    parser.add_argument("--model", type=str, default="gpt-4o-mini")
    parser.add_argument("--summary", type=str, default=SAMPLE_SUMMARY)
    parser.add_argument("--batch", action="store_true",
                        help="Run get_batch_scus() against a small built-in batch sample.")
    parser.add_argument("--clip", type=int, default=1,
                        help="Number of batches to split the inputs into (used with --batch).")
    return parser.parse_args()

if __name__ == "__main__":
    args = get_args()
    if args.batch:
        scus_res = get_batch_scus(SAMPLE_BATCH_SUMMARIES, args.model, clip=args.clip)
        print(f"Batch SCUs for the sample batch summaries:\n{scus_res}")
    else:
        scus = get_scus(args.summary, args.model)
        print(f"SCUs for the provided summary:\n{scus}")